# Builder stage
FROM golang:1.20-alpine AS builder

WORKDIR /app

# Copy only necessary files
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go generate ./ent
RUN go build -o main .

# Final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/public ./public

EXPOSE 8080

# Use ENTRYPOINT to make it easy to pass arguments to your application
ENTRYPOINT ["./main"]